version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: eu-pescador-fishlog
    expose:
      - '4001'
    ports:
      - '4001:4001'
    command: npm run dev
  db:
    container_name: postgresDbLog
    image: "postgres:latest"
    restart: always
    volumes:
      - ./fishLog:/data/db
    command: postgres -c port=5434
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5434:5434'